spring:
  profiles:
    active: development

---

spring:
  profiles: development
  datasource:
      password: 'pass'
      url: 'jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC'
      username: 'root'
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
  ldap:
    embedded:
      port: 8389
      ldif: 'classpath:ldap-data.ldif'
      base-dn: 'dc=springframework,dc=org'
server:
  port: 8080
name: devel-YAML
  spring.ldap.embedded.port=8389
  spring.ldap.embedded.ldif=classpath:ldap-data.ldif
  spring.ldap.embedded.base-dn=dc=springframework,dc=org

---

spring:
  profiles: prod
  datasource:
      password: 'pass'
      url: 'jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC'
      username: 'root'
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
server:
  port: 9092
name: prod-YAML