spring:
  profiles:
    active: development

---

spring:
  profiles: development
  datasource:
      password: 'pass'
      url: 'jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC'
      username: 'root'
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
server:
  port: 8080
name: devel-YAML

---

spring:
  profiles: prod
  datasource:
      password: 'pass'
      url: 'jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC'
      username: 'root'
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
server:
  port: 9092
name: prod-YAML